# Generated by Django 6.0.2 on 2026-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('event', 'Event'), ('general', 'General'), ('urgent', 'Urgent')], default='general', max_length=20)),
                ('priority_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
